language: node_js

node_js:
   - "10"

cache:
  yarn: true

install:
  - yarn install

script:
  - npm run build

deploy:
  local_dir: dist/
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: false
  name: zhangjian640
  email: 475218106@qq.com
  on:
    branch: master
